name: .NET

on: [push, pull_request]

jobs:
  build_iolaus:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: src 
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/cryptidsoftware/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.10
      with:
        versionSpec: '5.x'
    - name: Write Version
      uses: gittools/actions/gitversion/execute@v0.9.10
      with:
        useConfigFile: true
        configFilePath: src/GitVersion.yml
        additionalArguments: '/updateprojectfiles'
    - name: Restore dependencies
      run: dotnet restore Iolaus/Iolaus.csproj
    - name: Build
      run: dotnet build --no-restore Iolaus/Iolaus.csproj
    - name: Test
      run: dotnet test Iolaus.Tests --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release Iolaus/Iolaus.csproj
    - name: Publish
      run: dotnet nuget push Iolaus/bin/Release/*.nupkg

  build_iolaus_observer:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: src 
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/cryptidsoftware/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.10
      with:
        versionSpec: '5.x'
    - name: Write Version
      uses: gittools/actions/gitversion/execute@v0.9.10
      with:
        useConfigFile: true
        configFilePath: src/GitVersion.yml
        additionalArguments: '/updateprojectfiles'
    - name: Restore dependencies
      run: dotnet restore Iolaus.Observer/Iolaus.Observer.csproj
    - name: Build
      run: dotnet build --no-restore Iolaus.Observer/Iolaus.Observer.csproj
    - name: Pack
      run: dotnet pack --configuration Release Iolaus.Observer/Iolaus.Observer.csproj
    - name: Publish
      run: dotnet nuget push Iolaus.Observer/bin/Release/*.nupkg